move llvm-git-exp to llvm-git, update calamares pkgrel
Signed-off-by: Peter Jung <admin@ptr1337.dev>

diff --git a/llvm-git/PKGBUILD b/llvm-git/PKGBUILD
--- a/llvm-git/PKGBUILD
+++ b/llvm-git/PKGBUILD
@@ -1,51 +1,37 @@
-# Maintainer: Reza Jahanbakhshi <reza.jahanbakhshi at gmail dot com
-# Contributor: Lone_Wolf <lone_wolf@klaas-de-kat.nl>
-# Contributor: yurikoles <root@yurikoles.com>
-# Contributor: bearoso <bearoso@gmail.com>
-# Contributor: Luchesar V. ILIEV <luchesar%2eiliev%40gmail%2ecom>
-# Contributor: Anders Bergh <anders@archlinuxppc.org>
-# Contributor: Armin K. <krejzi at email dot com>
-# Contributor: Christian Babeux <christian.babeux@0x80.ca>
-# Contributor: Jan "heftig" Steffens <jan.steffens@gmail.com>
-# Contributor: Evangelos Foutras <evangelos@foutrelis.com>
-# Contributor: Hesiod (https://github.com/hesiod)
-# Contributor: Roberto Alsina <ralsina@kde.org>
-# Contributor: Thomas Dziedzic < gostrc at gmail >
-# Contributor: Tomas Lindquist Olsen <tomas@famolsen.dk>
-# Contributor: Tomas Wilhelmsson <tomas.wilhelmsson@gmail.com>
 
-
-pkgname=('llvm-git' 'llvm-libs-git')
-pkgver=16.0.0_r432912.a5d981045de7
+pkgname=llvm-git
+pkgdesc="LLVM Toolchain with clang, clang-tools-extra, compiler-rt, openmp, polly, lldb, lld"
+pkgver=16.0.0_r436660.525a400c7ca5
 pkgrel=1
 arch=('x86_64')
 url="https://llvm.org/"
 license=('custom:Apache 2.0 with LLVM Exception')
-makedepends=('git' 'cmake' 'ninja' 'libffi' 'libedit' 'ncurses' 'libxml2' 'python-sphinx'
-             'python-sphinx-automodapi' 'lldb' 'ocaml' 'ocaml-ctypes' 'ocaml-findlib'
-             'python-sphinx' 'python-recommonmark' 'swig' 'python' 'python-six' 'lua53'
-             'ocl-icd' 'opencl-headers' 'z3' 'jsoncpp' 'ocaml-stdlib-shims' 'llvm' 'llvm-libs' 'clang' 'lld' 'python-setuptools')
-checkdepends=("python-psutil")
-source=("llvm-project::git+https://github.com/llvm/llvm-project.git"
-        "llvm-config.h"
-        "only-invoke-DiagnoseNullConversions-for-CPlusPlus.patch")
-md5sums=('SKIP'
-         '295c343dcd457dc534662f011d7cff1a'
-         '86b7675857cf3128ca98b57837b372a9')
-sha512sums=('SKIP'
-            '75e743dea28b280943b3cc7f8bbb871b57d110a7f2b9da2e6845c1c36bf170dd883fca54e463f5f49e0c3effe07fbd0db0f8cf5a12a2469d3f792af21a73fcdd'
-            '2a5d6583e0783c041db4218ad725728dc349b5673d0370a51b1cc3ab1ff7114457a2d480590212ffec53c67d00ddfd65855fd784ac972885c462cc1e306292da')
+
+provides=('aur-llvm-git' 'compiler-rt-git' 'clang-git' 'lldb-git' 'lld-git' 'polly-git' 'aur-llvm-libs-git' 
+		  'llvm-libs' 'polly-git' 'openmp-git' 'mlir-git' 'pstl-git'
+		  'llvm' 'compiler-rt' 'clang' 'lldb' 'polly' 'lld' 'openmp' 'pstl' 'mlir' 'libc++' 'libc++abi' 'libc++experimental')
+# A package always provides itself, so there's no need to provide llvm-git
+conflicts=('llvm' 'compiler-rt' 'clang' 'lldb' 'polly' 'lld' 'llvm-libs' 'openmp' 'pstl' 'mlir' 'libc++abi' 'libc++experimental' 'libc++')
+depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses')
+_ocaml_ver=4.13.1
+makedepends=(
+    'git' 'ninja' 'cmake'
+    "ocaml>=${_ocaml_ver}" 'ocaml-ctypes' 'ocaml-findlib'
+    'python-setuptools' 'python-psutil' 'python-sphinx'
+    'python-recommonmark' 'clang' 'lld' 'llvm-libs' 'llvm' 'mold'
+)
+makedepends_x86_64=('lib32-gcc-libs')
+source=(
+    "llvm-project::git+https://github.com/llvm/llvm-project.git"
+    'llvm-config.h'
+    'improve-kernel-compile.patch'
+)
+
+sha256sums=('SKIP'
+            '597dc5968c695bbdbb0eac9e8eb5117fcd2773bc91edf5ec103ecffffab8bc48'
+            '593ed385298623711070dffce9225cb448dfc29f30c9d950887882b19bd124fb')
+
 options=('staticlibs')
-
-# NINJAFLAGS is an env var used to pass commandline options to ninja
-# NOTE: It's your responbility to validate the value of $NINJAFLAGS. If unsure, don't set it.
-# NINJAFLAGS="-j20"
-
-_python_optimize() {
-  python -m compileall "$@"
-  python -O -m compileall "$@"
-  python -OO -m compileall "$@"
-}
 
 pkgver() {
     cd llvm-project/llvm
@@ -55,141 +41,175 @@ pkgver() {
     local _pkgver=$(awk -F 'MAJOR |MINOR |PATCH |)' \
             'BEGIN { ORS="." ; i=0 } \
              /set\(LLVM_VERSION_/ { print $2 ; i++ ; if (i==2) ORS="" } \
-             END { print "\n" }' \
-             CMakeLists.txt)_r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
+            END { print "\n" }' \
+        CMakeLists.txt)_r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
     echo "$_pkgver"
 }
+
+_rpatch() {
+
+    echo -e "\E[1;33m Revert patch: ${1}\E[0m"
+    patch --forward --reverse --strip=1 --input="${srcdir:?}/${1}"
+
+}
+
+_patch() {
+
+    echo -e "\E[1;33m Apply patch: ${1}\E[0m"
+    patch --forward --strip=1 --input="${srcdir:?}/${1}"
+
+}
+
 prepare() {
-    cd llvm-project
-    ## Speedup kernel builds https://reviews.llvm.org/D131532
-    patch -Np1 < ../only-invoke-DiagnoseNullConversions-for-CPlusPlus.patch
-}
-build() {
-        export CC=clang
-        export CXX=clang++  
-    export CFLAGS+=" ${CPPFLAGS}"
-    export CXXFLAGS+=" ${CPPFLAGS}"
-    cmake \
-        -B _build \
-        -S "$srcdir"/llvm-project/llvm  \
-        -G Ninja \
-        -D CMAKE_BUILD_TYPE=Release \
-        -D CMAKE_INSTALL_PREFIX=/usr \
-        -D LLVM_BINUTILS_INCDIR=/usr/include \
-        -D LLVM_APPEND_VC_REV=ON \
-        -D LLVM_VERSION_SUFFIX="" \
-        -D LLVM_HOST_TRIPLE=$CHOST \
-        -D LLVM_ENABLE_RTTI=ON \
-        -D LLVM_ENABLE_FFI=ON \
-        -D FFI_INCLUDE_DIR:PATH="$(pkg-config --variable=includedir libffi)" \
-        -D LLVM_BUILD_LLVM_DYLIB=ON \
-        -D LLVM_LINK_LLVM_DYLIB=ON \
-        -D LLVM_INSTALL_UTILS=ON \
-        -D LLVM_BUILD_DOCS=ON \
-        -D LLVM_USE_LINKER=lld \
-        -D LLVM_ENABLE_BINDINGS=OFF \
-        -D LLVM_ENABLE_DOXYGEN=OFF \
-        -D LLVM_ENABLE_SPHINX=ON \
-        -D SPHINX_OUTPUT_HTML:BOOL=OFF \
-        -D SPHINX_WARNINGS_AS_ERRORS=OFF \
-        -D POLLY_ENABLE_GPGPU_CODEGEN=ON \
-        -D LLDB_USE_SYSTEM_SIX=1 \
-        -D LLVM_ENABLE_PROJECTS="polly;lldb;lld;compiler-rt;clang-tools-extra;clang" \
-        -D LLVM_LIT_ARGS="-sv --ignore-fail" \
-        -Wno-dev
 
-    ninja -C _build $NINJAFLAGS
-}
-
-check() {
-    ninja -C _build $NINJAFLAGS check-llvm
-    ninja -C _build $NINJAFLAGS check-clang
-    ninja -C _build $NINJAFLAGS check-clang-tools
-    ninja -C _build $NINJAFLAGS check-polly
-    ninja -C _build $NINJAFLAGS check-lld
-    ninja -C _build $NINJAFLAGS check-lldb
-}
-
-package_llvm-git() {
-    pkgdesc="LLVM development version. includes clang and many other tools"
-    depends=("llvm-libs-git=$pkgver-$pkgrel" 'perl')
-    optdepends=('python: for scripts'
-                'python-setuptools: for using lit = LLVM Integrated Tester'
+    cd "${srcdir:?}/llvm-project" || (
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
+        exit 1
     )
-    provides=(aur-llvm-git compiler-rt-git clang-git lldb-git lld-git polly-git
-              llvm compiler-rt clang lldb polly lld)
-    # A package always provides itself, so there's no need to provide llvm-git
-    conflicts=('llvm' 'compiler-rt' 'clang' 'lldb' 'polly' 'lld')
-    
-    DESTDIR="$pkgdir" ninja -C _build $NINJAFLAGS install
 
-    # Include lit for running lit-based tests in other projects
-    pushd llvm-project/llvm/utils/lit
-    python setup.py install --root="$pkgdir" -O1
-    popd
-    
-    # Move analyzer scripts out of /usr/libexec
-    mv "$pkgdir"/usr/libexec/{ccc,c++}-analyzer "$pkgdir"/usr/lib/clang/
-    mv "$pkgdir"/usr/libexec/analyze-{cc,c++} "$pkgdir"/usr/lib/clang/
-    mv "$pkgdir"/usr/libexec/intercept-{cc,c++} "$pkgdir"/usr/lib/clang/
-    rmdir "$pkgdir"/usr/libexec
-    sed -i 's|libexec|lib/clang|' "$pkgdir"/usr/bin/scan-build
+    _patch improve-kernel-compile.patch
+    # Attempt to convert script to Python 3
+    2to3 -wn --no-diffs \
+        clang-tools-extra/clang-include-fixer/find-all-symbols/tool/run-find-all-symbols.py
 
-    # The runtime libraries go into llvm-libs-git
-    mv -f "$pkgdir"/usr/lib/lib{LLVM,LTO,Remarks}*.so* "$srcdir"
-    mv -f "$pkgdir"/usr/lib/LLVMgold.so "$srcdir"
-
-    # OCaml bindings go to a separate package
-    rm -rf "$srcdir"/ocaml.{lib,doc}
-
-    
-        # Needed for multilib (https://bugs.archlinux.org/task/29951)
-        # Header stub is taken from Fedora
-        mv "$pkgdir"/usr/include/llvm/Config/llvm-config{,-64}.h
-        cp "$srcdir"/llvm-config.h "$pkgdir"/usr/include/llvm/Config/llvm-config.h
-
-    _py="3.10"
-    cd llvm-project
-    # Install Python bindings and optimize them
-    cp -a llvm/bindings/python/llvm  "$pkgdir"/usr/lib/python$_py/site-packages/
-    cp -a clang/bindings/python/clang  "$pkgdir"/usr/lib/python$_py/site-packages/
-    _python_optimize "$pkgdir"/usr/lib/python$_py/site-packages
-
-    #optimize other python files except 2 problem cases
-    _python_optimize "$pkgdir"/usr/share -x 'clang-include-fixer|run-find-all-symbols'
-
-    install -Dm644 llvm/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/llvm-LICENSE
-    install -Dm644 clang/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/clang-LICENSE
-    install -Dm644 clang-tools-extra/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/clang-tools-extra-LICENSE
-    install -Dm644 compiler-rt/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/compiler-rt-LICENSE
-    install -Dm644 lld/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/lld-LICENSE
-    install -Dm644 lldb/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/lldb-LICENSE
-    install -Dm644 polly/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/polly-LICENSE
 }
 
-package_llvm-libs-git() {
-    pkgdesc="runtime libraries for llvm-git"
-    depends=('gcc-libs' 'zlib' 'libffi' 'libedit' 'ncurses' 'libxml2' 'z3' 'lua53')
-    provides=(aur-llvm-libs-git llvm-libs)
-    conflicts=('llvm-libs')
+build() {
 
-    install -d "$pkgdir"/usr/lib
-    cp -P \
-        "$srcdir"/lib{LLVM,LTO,Remarks}*.so* \
-        "$srcdir"/LLVMgold.so \
-        "$pkgdir"/usr/lib/
+    cd "${srcdir:?}/llvm-project" || (
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Build Failed! \E[0m"
+        exit 1
+    )
+
+    if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]"; then
+        export CC=clang
+        export CXX=clang++
+        export AR=llvm-ar
+        export AS=llvm-as
+        export NM=llvm-nm
+        export STRIP=llvm-strip
+        export OBJCOPY=llvm-objcopy
+        export OBJDUMP=llvm-objdump
+        export READELF=llvm-readelf
+        export HOSTCC=clang
+        export HOSTCXX=clang++
+        export HOSTAR=llvm-ar
+        export DEBUG_CFLAGS="-g"
+        export DEBUG_CXXFLAGS="-g"
+        _extra_build_flags+=(
+            -DCMAKE_C_COMPILER=clang
+            -DCMAKE_CXX_COMPILER=clang++
+        )
+    else
+        echo -e "\E[1;31mClang not found. Will use default system compiler! \E[0m"
+    fi
+
+    if ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+        export LD=ld.lld
+        export CC_LD=lld
+        export CXX_LD=lld
+        export HOSTLD=ld.lld
+        _extra_build_flags+=(-DLLVM_USE_LINKER=lld)
+    fi
+
+    cmake -S llvm -B build -G Ninja \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DCMAKE_INSTALL_PREFIX=/usr \
+        -DLLVM_BINUTILS_INCDIR=/usr/include \
+        -DLLVM_HOST_TRIPLE="${CHOST:?}" \
+        -DLLVM_BUILD_RUNTIME=ON \
+        -DLLVM_BUILD_LLVM_DYLIB=ON \
+        -DLLVM_LINK_LLVM_DYLIB=ON \
+        -DCLANG_LINK_CLANG_DYLIB=ON \
+        -DLLVM_INSTALL_UTILS=ON \
+        -DLLVM_ENABLE_RTTI=ON \
+        -DLLVM_BUILD_DOCS=OFF \
+        -DLLVM_ENABLE_FFI=ON \
+        -DLLVM_ENABLE_BINDINGS=OFF \
+        -DLLVM_POLLY_LINK_INTO_TOOLS=ON \
+        -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;lldb;mlir;polly;pstl" \
+        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;openmp;compiler-rt" \
+        -DCLANG_LINK_CLANG_DYLIB=ON \
+        -DLLDB_USE_SYSTEM_SIX=1 \
+        -DLIBOMP_INSTALL_ALIASES=OFF \
+        -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
+        -DPOLLY_ENABLE_GPGPU_CODEGEN=ON \
+        -DCLANG_DEFAULT_PIE_ON_LINUX=ON \
+        "${_extra_build_flags[@]}"
+
+    ninja -C build
+
+
+}
+
+_python_optimize() {
+    python -m compileall "$@"
+    python -O -m compileall "$@"
+    python -OO -m compileall "$@"
+}
+
+package() {
+
+    cd "${srcdir:?}/llvm-project" || (
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Package Failed! \E[0m"
+        exit 1
+    )
+
+    if [[ _build_documentation -eq 0 ]]; then
+        mkdir -p "${srcdir:?}/llvm-project/build/docs/ocamldoc/html/"
+    fi
+
+    DESTDIR="${pkgdir:?}" ninja -C build install
+
+    pushd llvm/utils/lit || (
+        echo -e "\E[1;31mpushd utils/lit - Package Failed! \E[0m"
+        exit 1
+    )
+
+    python setup.py install --root="${pkgdir:?}" -O1
+    popd || (
+        echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+        exit 1
+    )
+
+    if [[ "${CARCH:?}" == "x86_64" ]]; then
+        mv "${pkgdir:?}/usr/include/llvm/Config/llvm-config"{,-64}.h
+        cp "${srcdir:?}/llvm-config.h" "${pkgdir:?}/usr/include/llvm/Config/llvm-config.h"
+    fi
 
     # Symlink LLVMgold.so from /usr/lib/bfd-plugins
     # https://bugs.archlinux.org/task/28479
-    install -d "$pkgdir"/usr/lib/bfd-plugins
-    ln -s ../LLVMgold.so "$pkgdir"/usr/lib/bfd-plugins/LLVMgold.so
-    
-    cd llvm-project/
-    install -Dm644 llvm/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/llvm-LICENSE
-    install -Dm644 clang/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/clang-LICENSE
-    install -Dm644 clang-tools-extra/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/clang-tools-extra-LICENSE
-    install -Dm644 compiler-rt/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/compiler-rt-LICENSE
-    install -Dm644 lld/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/lld-LICENSE
-    install -Dm644 lldb/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/lldb-LICENSE
-    install -Dm644 polly/LICENSE.TXT "$pkgdir"/usr/share/licenses/$pkgname/polly-LICENSE
+    mkdir -p "${pkgdir:?}/usr/lib/bfd-plugins"
+    ln -s ../LLVMgold.so "${pkgdir:?}/usr/lib/bfd-plugins/LLVMgold.so"
+
+    # Clang
+    site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
+    install -d "${pkgdir:?}/${site_packages}"
+    mv "${pkgdir:?}/usr/lib/"{libear,libscanbuild} "${pkgdir:?}/${site_packages}/"
+    cp -a llvm/bindings/python/llvm "${pkgdir:?}/${site_packages}/"
+    cp -a clang/bindings/python/clang "${pkgdir:?}/${site_packages}/"
+
+    mv "${pkgdir:?}"/usr/libexec/* "${pkgdir:?}/usr/lib/clang/"
+    rm -fr "${pkgdir:?}/usr/libexec"
+    sed -i 's|libexec|lib/clang|' \
+        "${pkgdir:?}/usr/bin/scan-build" \
+        "${pkgdir:?}/${site_packages}/libscanbuild/analyze.py"
+
+    _python_optimize "${pkgdir:?}/usr/share" "${pkgdir:?}/${site_packages}"
+
+    # Remove html documentation
+    if [[ _build_documentation -eq 0 ]]; then
+        rm -fr "${pkgdir:?}/usr/share/doc"
+    fi
+
+    # Licenses
+    install -Dm644 "${srcdir:?}/llvm-project/llvm/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/llvm-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/clang/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/clang-tools-extra/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-tools-extra-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/compiler-rt/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/compiler-rt-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/lld/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lld-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/lldb/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lldb-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/polly/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/polly-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/openmp/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/openmp-LICENSE"
+
 }
